name: Update file
on:
  push:
    branches:
      - main

jobs:
    push:
     runs-on: ubuntu-latest

     steps:
      - name: checkout test-commits
        uses: actions/checkout@v3
      - name: checkout test-gitops
        run:  git clone https://swathiwohlig:${{ secrets.ACTIONS_GITHUB_TOKEN }}@github.com/swathiwohlig/second.git
      - name: configure git
        run: |
          git config --global user.email "swathi.cherala@wohlig.com"
          git config --global user.name "swathiwohlig"
      - name: Update test.txt
        run: |
          cd second
 
          commit_count=$(grep -oP '(?<=commit count is : )\d+' test.txt)
          new_commit_count=$((commit_count + 50))
          
          echo "hello i am devops" > test.txt
          echo "my commit count is : $new_commit_count" >> test.txt
          echo "thank you" >> test.txt
 
          git add .
          git commit -m "update new count"
          git push origin main

