name: Update file
on:
  push:
    branches:
      - main

jobs:
    push:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v2

       - name: Update File
         run: | 
          count=$(($(cat second-test.txt | grep -oP '(\d+)' || echo 0) + 50))
          echo "hello i am devops" > updated-test.txt
          echo "my commit count is : $count" >> updated-file.txt
          echo "thank you" >> updated-test.txt
       - name: setup git config
         run: |
          git config --global user.email "swathi.cherala@wohlig.com"
          git config --global user.name "swathiwohlig"
          git add updated-test.txt
          git commit -m “Increased count by 50 numbers" 
          - run: git push origin main



