name: Update file
on:
  push:
    branches:
      - main

jobs:
    push:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v2

       - name: Update File
         run: | 
          count=$(($(cat second-test.txt | grep -oP '(\d+)' || echo 0) + 50))
          echo "hello i am devops"
          echo "my commit count is : $count"
          echo "thank you"
       - name: setup git config
         run: |
          git config --global user.email "swathi.cherala@wohlig.com"
          git config --global user.name "swathiwohlig"
          git add test.txt
          git commit -m “Incremented by 50" 
          - run: git push origin main



