name: Update file
on:
  push:
    branches:
      - main

jobs:
    push:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout Repository
         uses: actions/checkout@v2
         with:
          repository: swathiwohlig/first

       - name: Update File
         run: | 
          count=$(($(cat test.txt | grep -oP '(\d+)' || echo 0) + 50))
          echo "hello i am devops" > test.txt
          echo "my commit count is : $count" >> test.txt
          echo "thank you"

       - name: Commit and Push Changes
         run: |
          git config --global user.email "swathi.cherala@wohlig.com"
          git config --global user.name "swathiwohlig"
          git add test.txt
          git commit -m "Incremented by 50 number" 
          - run: git push origin main



