name: Update file
on:
  push:
    branches:
      - main

jobs:
    push:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout Repository
         uses: actions/checkout@v2

       - name: Update File
         run: | 
          git clone https://${{ secrets.ACTIONS_GITHUB_TOKEN }}@github.com/swathiwohlig/second.git
          echo ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          cd second
          git checkout main
          count=$(($(grep -oP 'my commit count is : \K\d+' test.txt) + 50))
          sed -i "s/my commit count is : $count/my commit count is : $count/" test.txt
          cat test.txt
          git config --global user.email "swathi.cherala@wohlig.com"
          git config --global user.name "swathiwohlig"
          git add .
          git commit -m "Incremented by 50 " 
          git push origin main 

