name: Update file
on:
  push:
    branches:
      - main

jobs:
    push:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout Repository
         uses: actions/checkout@v2
         with:
           repository: swathiwohlig/second
           path: reoB

       - name: Update File
         run: | 
          count=$(grep -oP 'my commit count is : \K\d+' test.txt)
          new_count=$((count + 50))
          sed -i "s/my commit count is : $count/my commit count is : $new_count/" test.txt

       - name: Commit and Push Changes
         run: |
          git config --global user.email "swathi.cherala@wohlig.com"
          git config --global user.name "swathiwohlig"
          git commit -m "Incremented by 50 number" 
          git push
         env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}



